### ISSUE TITLE
[catloop] Ring Buffer Should Support Multiple Producers

### ISSUE THREAD

**Issue by ppenna** [microsoft/demikernel#842]
## Description

Catloop LibOS assumes that `RingBuffer` supports multiple concurrent producers, but it does not.

We currently assume this on the connection establishment protocol.

## Code Snippets

In the code snippet bellow, we do not support multiple producers, because there is a race condition when updating the back pointer:

https://github.com/microsoft/demikernel/blob/d9798065dfd8c600be44bf79e49d68b797195ba4/src/rust/collections/ring.rs#L192-L211

## Expected Behavior

We either:

- Fix Catlop LibOS to not rely on this assumption
- Fix `RingBuffer` implementation to support multiple producers.

**Comment by iyzhang** [comment]
Do we want to support multiple producers within a single process or across multiple processes?

**Comment by iyzhang** [comment]
Here is my suggestion for this PR and #859: We build in support for variable length buffers at the shared_ring level to minimize the number of atomic operations that we need to do. Doing so will also enable us to place framing around each object because we will be able to amortize the header cost over the entire buffer and we will be able to do a single copy of the buffer into the ring. I understand that we originally did not want to do this because we expected the shared_ring to only carry meta-data but if we have a solid implementation at this level, we can re-use the same code for a RDMA shared ring buffer. 

I took a look at Section 3.1 of this paper and believe the following implementation would work for RDMA as well. 
1. We keep a front and back pointer and use fetch_add instructions to atomically update them, producers share the back pointer and consumers share the front pointer.
2. We place a 32-bit header between each variable sized message that contains a magic number followed by a length. 
3. To enqueue, we fetch_add the back pointer to reserve space, then write the buffer first and then atomically write the header. The header indicates that the buffer is now ready to read.
4. On dequeue, we poll the header at the front pointer and wait until the value is non-zero there. Since the header contains a magic number and a length, both should be non-zero. To dequeue, we zero the header and move the front pointer.

Having a per-message header lets us avoid keeping another atomic pointer that we have to check and is more robust to miscalculations. Having variable length messages lets us perform I/O more efficiently and amortize the cost of the header over the whole buffer.

**Comment by ppenna** [comment]
> Do we want to support multiple producers within a single process or across multiple processes?

Currently no, eventually yes.
